version: '3'

services:
  nodejs:
    build:
      context: ./reto-devops
      dockerfile: Dockerfile
    image: doxk91/reto-devops
    container_name: reto-devops_app
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3000:3000"

  webserver:
     build:
        context: ./web_proxy/nginx-conf/
        dockerfile: Dockerfile
     image: doxk91/reto-devops_web
     container_name: reto-devops_web
     ports:
         - "80:80"
         - "443:443"
     restart: always
     depends_on:
        - nodejs
     networks:
        - app-network
        
#  certbot:
#        image: certbot/certbot:latest
#        command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@domain.com --agree-tos --no-eff-email -d localhost -d localhost
#        volumes:
#            - ./certbot/conf:/etc/letsencrypt
#            - ./certbot/logs:/var/log/letsencrypt
#            - ./certbot/data:/var/www/certbot
networks:
  app-network:
    external: true
